version: "3.8"
services:
  app:
    build: .
    container_name: pet_adoption-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://db:1433;databaseName=projectDB
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: YourStrong@Passw0rd
      SPRING_JPA_HIBERNATE_DDL_AUTO: create

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-db
  environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=${MSSQL_SA_PASSWORD}
    - MSSQL_COLLATION=Thai_100_CI_AS_SC_UTF8
  ports:
    - "1433:1433"
  volumes:
    - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql